# Dots OCR has been officially integrated into vLLM since v0.11.0
# Below is the dockerfile for out-of-tree model registration support based on v0.9.1
from vllm/vllm-openai:v0.9.1

RUN pip3 install flash_attn==2.8.0.post2
RUN pip3 install transformers==4.51.3
